### ISSUE TITLE
Client name doesn't change on invoice tab when changed through clickthrough in client tab

### ISSUE THREAD

**Issue by Thomasjanssens001** [itenium-be/confac#217]
Bij eender welke factuur (factuur #4 in testomgeving gebruikt voor deze bugtest) heb je, naast de naam van de klant, 2 knoppen (![image_2023-03-01_143726715](https://user-images.githubusercontent.com/126571964/222154394-aeb05d3c-d1f9-4bc9-8bc8-b8f3ad8af99b.png). Via beide knoppen kan je de info van de factuur en de klant aanpassen. Wanneer je op de rechtse knop klikt, kom je op de gedetaileerde klanteninfo. Wanneer je op deze tab de naam van de klant verandert, verandert deze niet in het detailvakje op de facturatietab. De naam verandert wel in de dropdown lijst voor de klant op de facturatietab. Ik zou aannemen dat de naam in het detailvakje ook zou veranderen.

Indien de naam veranderd is kan deze opnieuw veranderd worden. Wanneer er op de eerste knop gedrukt wordt (![image](https://user-images.githubusercontent.com/126571964/222158732-aa1148b8-1d10-497c-989f-b452196a4016.png) , dan op de knop 'Bewaren', veranderd de naam van de klant in de dropdown terug naar de naam die in het detailvakje staat.

Steps to reproduce: 
1. navigeer naar tab "facturen"
2. klik factuur nummer 4 (Cormier-Brown) aan
3. klik op tweede link naar de naam Cormier-Brown in het detailvakje (![image](https://user-images.githubusercontent.com/126571964/222157092-d2dc2bba-bc58-4b73-9a4d-834ff15fdc66.png)
4. verander de naam van Cormier-Brown naar iets anders 
5. navigeer terug naar factuur nummer 4
6. de naam verandert enkel in de dropdown maar niet in het detailvakje
7. klik op de eerste link naast de naam Cormier-Brown in het detailvakje  ![image](https://user-images.githubusercontent.com/126571964/222160029-4fca7e5c-ff0c-4293-9380-1716b3081668.png)
8. klik op "Bewaren"
9. de naam van de klant in de dropdown verandert in de naam in het detailvakje 

Expected result:
1. idem 1
2. idem 2
3. idem 3
4. idem 4
5. idem 5
6. de naam in het detailvakje verandert naargelang de verandering in de klanttab

Deze bug is geen showstopper, dus low prio.
De effort om deze bug te fixen kan ik niet exact inschatten maar deze lijkt mij niet groot. 
Deze bug doet zich voor in de testomgeving.

**Comment by Laoujin** [comment]
Bij een factuur (vb factuur #4 in test) heb je, naast de naam van de klant, 2 knoppen om de details van de klant aan te passen:

 (![image_2023-03-01_143726715](https://user-images.githubusercontent.com/126571964/222154394-aeb05d3c-d1f9-4bc9-8bc8-b8f3ad8af99b.png). 

## Inconsistent behavior

**Rechts Icon:**
- Gaat naar het klant editeer scherm
- Pas de naam aan
- Keer terug naar factuur details
--> Naam is aangepast in de klantdropdown maar heeft nog de oude waarde in de details label eronder

**Links Icon:**
- Opent klant details in modal
- Pas de naam aan
- Bewaren sluit de modal
--> Naam is aangepast in de klantdropdown EN ook in de label

**Comment by stevenrobijns** [comment]
Even een snelle assessment: 

> Bij eender welke factuur
"Bij eender welke factuur op het factuurdetailscherm"

> Wanneer je op de rechtse knop klikt,
"Wanneer je op de rechterknop klikt"

Ik vind het format al niet slecht, maar te tekstueel soms.
Het lijkt ook dat 2 bugs hier in 1 issue gestopt worden?
2 knoppen met ieder een bug dienen 2 issues te worden?

Bevat wel al een aantal belangrijke elementen:
Steps to reproduce, expected result
Context & Actual zitten verweven. 

Veel tekst momenteel. Minder tekstueel maken best. Moet overzichtelijker. De afbeeldingen zijn groot waardoor het de regels minder leesbaar maakt. Afbeeldingen minder hoog creëren?

Er mag 1 screenshot bij van het gele scherm voor mij met aanduiding(goed dat je al arceert).

Ik zou volgend volgorde doen en ook werken met formatting(bold, etc..)

**Context:** 
Bij aanpassen van de naam van de klant wordt deze niet altijd goed weergegeven.

**Environment:**Test

**Steps To Reproduce:**

**Expected Result:**

**Actual Result:**

**Severity:** Non-blocking

**Prio:** Low

**Comment by fatihozdemir61** [comment]
Defect afgesloten naar aanleiding van onze meeting van 3/11/23. Workaround kan toegepast worden.
