### ISSUE TITLE
Strange behaviour when creating invoices

### ISSUE THREAD

**Issue by Thomasjanssens001** [itenium-be/confac#223]
## **Context:**
Bij specifieke acties verschijnen er enkele error meldingen. Het verwijderen en opnieuw aanmaken van een factuur gelinked aan hetzelfde project gaat gepaard met enkele errors.

### Error Nr1:
Error message: '$set' is empty: You must specify a field like so: {$set: {<field>: ...}}
![image](https://user-images.githubusercontent.com/126571964/222886123-ff742f02-cb93-47d8-9006-0304f9851ff5.png)

### Error Nr2:
Error message: E11000 duplicate key error collection: confac-test.attachments_project_month index: _id_dup key: { : ObjectId('63ff4e8a079cf99ae3d22c14') }
![image](https://user-images.githubusercontent.com/126571964/222886154-960f865f-dda0-488a-a742-8d25d9a3befb.png)

## **Steps To Reproduce:**
1. op het invoice scherm, maak een nieuwe factuur aan
2. navigeer naar het facturatiescherm en verwijder de net aangemaakte factuur
3. navigeer terug naar het facturatiescherm en maak voor hetzelfde project een factuur aan
4. error nr1 verschijnt
5. navigeer naar het facturatiescherm en refresh de pagina
6. nieuwe factuur verschijnt toch
7. klik op de knop om de factuur te verwijderen -> error nr2 verschijnt en de factuur kan niet verwijderd worden

## **Expected Result:**
de factuur zou aangemaakt en verwijderd moeten worden zonder errors

## **Actual Result:**
het aanmaken van de factuur voor de tweede keer gaat gepaard met een error, terwijl deze wel aangemaakt wordt. Het verwijderen van de factuur voor de tweede keer gaat ook gepaard met een error maar deze keer wordt de actie niet voltooid

**Comment by Laoujin** [comment]
Ook nog een belangrijk:
Als je een bug hebt met een foutmelding die niet door een human begrijpbaar is (vb: interne exception messages, niet vertaalde foutboodschappen, stack traces, ...) dan is het voor een dev altijd heel handig als je die als tekst mee in de bug report zet.

Typisch als het moeilijk is om de tekst te kopieren (vb omdat de toastr te snel weg is), kan je de volledig fout ook zijn in de developer console in de Console en/of in de Network tabs. (in network tab, check voor status code 500 InternalServerError)
