### ISSUE TITLE
Template 1 niet in orde

### ISSUE THREAD

**Issue by Thomasjanssens001** [itenium-be/confac#225]
## **Context**
Sommige zaken op het facturenscherm (vb. http://itenium.synology.me:9100/invoices/4) zijn niet terug te vinden op de template van de factuur.
# **Kortingen worden niet duidelijk getoond op pdf**
VB -> http://itenium.synology.me:9100/invoices/1
## **Visual**
![image](https://user-images.githubusercontent.com/126571964/223732152-59d91937-781d-4904-8ab9-d92dc6f7bb97.png)
![image](https://user-images.githubusercontent.com/126571964/223732240-149f8cdb-de01-487d-89a1-5d14b758c9b2.png)
## **Expected behavior**
Het is duidelijk hoeveel korting er gegeven wordt
## **Actual behavior**

De kortingen worden juist berekend maar op de PDF kan er niet teruggevonden worden over hoeveel korting dit gaat.
# **Te lang woord in omschrijving (vb. bepaald registratienummer of productnummer)**
## **Visual**
vb -> http://itenium.synology.me:9100/invoices/4
![image](https://user-images.githubusercontent.com/126571964/223732833-e7d66842-a5de-4a5d-b930-5c4b3490e334.png)
![image](https://user-images.githubusercontent.com/126571964/223732881-cb4dab76-0aa6-4ff0-8822-d4ec9e08a12e.png)
## **Expected behavior**
De tekst wordt gewrapped zodat de layout van de template niet aangepast wordt.
## **Actual behavior**
De tekst blijft naar rechts opschuiven, waardoor de prijsberekening niet meer zichtbaar wordt.

# **Te lange omschrijving (vb. veel woorden)**
link: http://itenium.synology.me:9100/invoices/15
## **Visual**
![image](https://user-images.githubusercontent.com/126571964/225324513-defcd13f-7d7c-453a-b6b4-747584e4ece4.png)
## **Expected behaviour**
De factuurlijnen worden overzichtelijk getoond
## **Actual behaviour**
De prijs gelinked aan de factuurlijnen volgen de opmaak van de factuur niet

# **BTW afwijkend van 21% niet duidelijk**
link: http://itenium.synology.me:9100/invoices/8
## **Visual**
![image](https://user-images.githubusercontent.com/126571964/225325031-d4e2c3df-2a15-4e3f-8e06-599f5a46bec3.png)
![image](https://user-images.githubusercontent.com/126571964/225325109-c16b981e-0590-48b8-99f7-c121a305266f.png)
## **Expected behaviour**
Er is een verduidelijking over de BTW gelinked aan een factuurlijn
## **Actual behaviour**
Wanneer de BTW afwijkt van 21% wordt dit juist berekend op de factuur maar er is geen verduidelijking op de factuur over de afwijking van de 21% BTW standaard, zelfs wanneer geen enkele factuurlijn 21% BTW heeft.

**Comment by Laoujin** [comment]
This could be interesting to fix when we sell confac to another company and are asked to give a VERY EXTENSIVE demo.
Or when we're doing A LOT of demos for many different potential customers. Meaning: the test template is used only by testers and by no one else.  We will not need a fully functionally test template for at least the next 2 years.

Typically, no one cares about the test template  -- a new template for the company that is buying confac will be created at that time.

**Comment by Laoujin** [comment]
We can't forget about the issues though...
