### ISSUE TITLE
Knop downloaden en factuur bekijken doen hetzelfde in sommige gevallen

### ISSUE THREAD

**Issue by Thomasjanssens001** [itenium-be/confac#227]
link: http://itenium.synology.me:9100/invoices/15
## **Visual**
![Capture](https://user-images.githubusercontent.com/126571964/225323247-19b9c830-4661-440c-8d27-da2d7105de02.PNG)

## **Expected behaviour**
De linkse knop (... Downloaden) moet de pdf downloaden en de rechtse knop (pdf factuur bekijken) opent een nieuw tab in browser om de pdf online te tonen.

## **Actual behaviour**
Op de laptop die op de bureau staat openen beide knoppen de pdf file in een nieuw tab. Beide knoppen werken dan weer wel op mijn vaste PC

**Comment by Laoujin** [comment]
Not an issue:

Configure the computer to be able to open a PDF in the browser and this will work.
