### ISSUE TITLE
Factuurdatum op invoices mag op de nieuwe maand vanaf de 22ste

### ISSUE THREAD

**Issue by stevenrobijns** [itenium-be/confac#283]
Vermoedelijk staat dit nu op de laatste dag van de maand.

Issue:
Als je op de 22ste van bvb juni een factuur maakt dan wordt de datum nog gezet op 1 mei 2024.
Dit zou op dat moment 1 juni 2024 mogen zijn.

**Comment by Laoujin** [comment]
![image](https://github.com/itenium-be/confac/assets/2582910/37a9abea-9694-4bff-818e-d5ebf490c478)

Add a new option to the dropdown for this new behavior

I think there might be tests for this...

**Comment by JochemVH1** [comment]
Effe dat ik het goed begrijp:

- Factuur aanmaken van 1-21 juni => factuur datum 1 mei
- Factuur aanmaken van 22-30 juni => factuur datum 1 juni

**Comment by Laoujin** [comment]
De omschrijving doesn't make any Sense denk ik
Check met Steven, ik vermoed dat het anders moet zijn

**Comment by JochemVH1** [comment]
Effe over gebabbeld met steven en hieruit is het volgende gekomen:
```
stel het is 1 januari en je maakt factuur dan moet hij laatste dag van de maand ervoor nemen, dus 31 december
stel het is 21 januari nog steeds 31 december (edited)
22 januari - 30 januari -> 1 januari
31 januari (elke laatste dag van de maand) tot 21 februari -> 31 januari factuurdatum
```
Dus in essentie:
1) 1ste tot 21ste van de maand => 31ste van de vorige maand
2) 22ste tot voorlaatste dag van de maand => 1ste van huidige maand
3) Laatste dag van de maand = laatste dag van de maand
