### ISSUE TITLE
Inheritance of email body

### ISSUE THREAD

**Issue by Laoujin** [itenium-be/confac#284]
![image](https://github.com/itenium-be/confac/assets/2582910/1520fadb-c933-48eb-9c2e-bad47b5dbb4b)

In productie is de email body voor een bepaalde klant overschreven. Nu lukt het niet meer om dit leeg te maken.

De lege tekst is wss iets ala "<span></span><span></span>" (ofzo)
Met dat dat niet "leeg" is wordt die tekst gebruikt (van de client) ipv de tekst van de config

We zouden een knopje nodig hebben ofzo om de tekst volledig te clearen (zodat opnieuw de tekst van de config genomen wordt)

**Comment by Laoujin** [comment]
Dit is een component, "TextEditor" ofzo, we zouden daar een extra knopje bij willen dat de tekst reset:

![image](https://github.com/itenium-be/confac/assets/2582910/517c9808-efdb-4895-92c0-7c1a464cf83a)

**Comment by JochemVH1** [comment]
Paar vraagjes nog:

Is dit gewenst bij elke TextEditor? of enkel bij de gene voor de facturatie email?
=> De logica is toegevoegd aan de TextEditorReplacements component omdat deze gebruikt wordt voor de custom knopjes toe te voegen aan de TextEditor, momenteel heb ik hier aan een optionele property aan toegevoegd zodat je kan instellen of je de clear knop wilt of niet

De clear werkt dus maar nog geen idee hoe ik een icoontje toevoeg aan de knop, any ideas?

![image](https://github.com/itenium-be/confac/assets/17174475/16d58e83-534b-4187-b700-2a335cae92e1)

**Comment by Laoujin** [comment]
Ja op alle TextEditos voorzien

Icon is misschien niet zo belangrijk, clear is voldoende
Kan je es kijken voor de size van de button zodat ie even hoog is als de andere?
